export const PlayerCard: string;
export const ChatCloud: string;
export const User: string;
export const UserInfo: string;
export const Balance: string;
export const UserInactive: string;
export const FloatLeft: string;
export const FloatRight: string;
export const FloatCenter: string;
