export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

export const GAME_MODE_ON = 'GAME MODE ON';
export const GAME_MODE_OFF = 'GAME MODE OFF';
export const SET_STANDALONE = 'SET_STANDALONE';
export const SET_GAME_BACK_PATH = 'SET_GAME_BACK_PATH';

export const PRESELECT_RAISE = 'PRESELECT_RAISE';

export const SELECT_TABLE = 'SELECT_TABLE';

// rest actions

export const FETCH_TABLES_START = 'FETCH_TABLES_START';
export const FETCH_TABLES_SUCCESS = 'FETCH_TABLES_SUCCESS';
export const FETCH_TABLES_FAIL = 'FETCH_TABLES_FAIL';

export const FETCH_PLAYERS_START = 'FETCH_PLAYERS_START';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';


export const SET_CURRENT_TABLE = 'SET_CURRENT_TABLE';


