export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

export const GAME_MODE_ON = 'GAME MODE ON';
export const GAME_MODE_OFF = 'GAME MODE OFF';
export const CHAT_MODE_ON = 'CHAT MODE ON';
export const CHAT_MODE_OFF = 'CHAT MODE OFF';
export const SET_STANDALONE = 'SET_STANDALONE';
export const SET_GAME_BACK_PATH = 'SET_GAME_BACK_PATH';

export const PRESELECT_RAISE = 'PRESELECT_RAISE';

export const SELECT_TABLE = 'SELECT_TABLE';

// rest actions

export const FETCH_TABLES_START = 'FETCH_TABLES_START';
export const FETCH_TABLES_SUCCESS = 'FETCH_TABLES_SUCCESS';
export const FETCH_TABLES_FAIL = 'FETCH_TABLES_FAIL';

export const FETCH_PLAYERS_START = 'FETCH_PLAYERS_START';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';


export const SET_CURRENT_TABLE = 'SET_CURRENT_TABLE';

export const INIT_DASHBOARD_START = 'INIT_DASHBOARD_START';
export const INIT_DASHBOARD_FAIL = 'INIT_DASHBOARD_FAIL';
export const INIT_DASHBOARD_SUCCESS = 'INIT_DASHBOARD_SUCCESS';



export const SELECT_SPIN = 'SELECT_SPIN';
export const SELECT_NEXT_SPIN = 'SELECT_NEXT_SPIN';
export const SELECT_SPIN_GAMES_NUMBER = 'SELECT_SPIN_GAMES_NUMBER';
export const LOBBY_SWITCH_VIEW = 'LOBBY_SWITCH_VIEW';
export const LOBBY_CHANGE_GAME_FILTER = 'LOBBY_CHANGE_GAME_FILTER';
export const LOBBY_CHANGE_BUYIN_FILTER = 'LOBBY_CHANGE_BUYIN_FILTER';
export const LOBBY_APPLY_FILTER = 'LOBBY_APPLY_FILTER';
export const LOBBY_RESET_FILTER = 'LOBBY_RESET_FILTER';
