export const TwoFronts: string;
export const Absolute: string;
export const SVGContainer: string;
export const SVGContainer_Small_Browser: string;
export const SVGContainer_Small_Browser_Dashboard: string;
export const SVGContainer_Small_Mobile: string;
export const SVGContainer_Small_Mobile_Dashboard: string;
export const SVGContainer_Large_Browser: string;
export const SVGContainer_Large_Mobile: string;
